- name: disbaling and old node js and enabling new nodejs
  shell: "{{ item }}"
  loop:
  - dnf module disable nodejs -y
  - dnf module enable nodejs:18 -y
  - dnf install node js

- name: Creating roboshop user
  user:
    name: roboshop
    state: present

- name: Creating App directory
  file:
    path: /app
    state: present   

- name: Downloading App Code
  get_url:
    url: "https://roboshop-builds.s3.amazonaws.com/{{ component }}.zip"
    dest: /tmp

- name: unzipping app copde
  unarchive:
    src: "/tmp/{{ component }}.zip"
    dest: /app
    remote_src: yes
  

- name: Npm Installation
  shell: npm install
  args:
    chdir: /app

- name: copying {{ component }} serive file
  copy:
    src: catalogue.service
    dest: "/etc/systemd/system/{{ component }}.service"

- name: RELOAD SYSTEMD DAEMON
  systemd:
    daemon_reexec: yes    

- name: Reaload and start the {{ component }}
  systemd:
    name: "{{ component }}"
    state: started

- name: COPY MONGO REPO FILE
  copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: INSTALL MONGODB SHELL
  dnf:
    name: mongodb-org-shell
    state: present

- name: VERIFY PRODUCTS COUNT
  command: mongo --host mongo.gonepudirobot.online --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
  register: product_count

- name: Print Product COUNT
  debug:
    msg: "Total Product_Count: {{ product_count.stdout_lines }}"    
