- name: app setup {{component}}
  import_role:
    name: common
    tasks_from: app-setup

- name: Nodejs setup
  import_role:
    name: common
    tasks_from: nodejs-setup 

- name: copying {{ component }} serive file
  copy:
    src: catalogue.service
    dest: "/etc/systemd/system/{{ component }}.service"
       
- name: mongo-setup
  import_role:
    name: common
    tasks_from: mongo-setup

- name: APP START SETUP 
  import_role:
    name: common
    tasks_from: systemd-setup   