- name: app setup {{component}}
  import_role:
    name: common
    tasks_from: app-setup

- name: Nodejs setup
  import_role:
    name: common
    tasks_from: nodejs-setup 

- name: copying {{ component }} serive file
  copy:
    src: catalogue.service
    dest: "/etc/systemd/system/{{ component }}.service"

- name: RELOAD SYSTEMD DAEMON
  systemd:
    daemon_reexec: yes    

- name: Reaload and start the {{ component }}
  systemd:
    name: "{{ component }}"
    state: started
    enabled: yes

- name: COPY MONGO REPO FILE
  copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: INSTALL MONGODB SHELL
  dnf:
    name: mongodb-org-shell
    state: present

- name: VERIFY PRODUCTS COUNT
  command: mongo --host mongo.gonepudirobot.online --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
  register: product_count

- name: Print Product COUNT
  debug:
    msg: "Total Product_Count: {{ product_count.stdout_lines }}"

- name: LOAD DATA INTO MONGODB
  shell: "mongo --host mongo.gonepudirobot.online < /app/schema/{{ component }}.js"
  when: product_count.stdout == "0" 

- name: RESTART CATALOGUE SERVICE
  systemd:
    name: "{{ component }}"
    state: restarted        
