- name: app setup {{component}}
  import_role:
    name: common
    tasks_from: app-setup

- name: Nodejs setup
  import_role:
    name: common
    tasks_from: nodejs-setup 

- name: copying {{ component }} serive file
  copy:
    src: catalogue.service
    dest: "/etc/systemd/system/{{ component }}.service"

- name: RELOAD SYSTEMD DAEMON
  systemd:
    daemon_reexec: yes    

- name: Reaload and start the {{ component }}
  systemd:
    name: "{{ component }}"
    state: started
    enabled: yes

- name: RESTART CATALOGUE SERVICE
  systemd:
    name: "{{ component }}"
    state: restarted        
