- name: COPY MONGO REPO FILE
  copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: INSTALL MONGODB SHELL
  dnf:
    name: mongodb-org-shell
    state: present

- name: VERIFY PRODUCTS COUNT
  command: mongo --host mongo.gonepudirobot.online --quiet --eval 'db = db.getSiblingDB("{{component}}"); db.products.count()'
  register: element_count
  when: componet == "catalogue"

- name: VERIFY PRODUCTS COUNT
  command: mongo --host mongo.gonepudirobot.online --quiet --eval 'db = db.getSiblingDB("{{component}}"); db.users.count()'
  register: element_count
  when: componet == "users"

- name: Print Product COUNT
  debug:
    msg: "Total element_count_Count: {{ element_count.stdout_lines }}"

- name: LOAD DATA INTO MONGODB
  shell: "mongo --host mongo.gonepudirobot.online < /app/schema/{{ component }}.js"
  when: product_count.stdout == "0" 